src/java/JP/VentaController.java
package JP;

import JP.util.JsfUtil;
import JP.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("ventaController")
@SessionScoped
public class VentaController implements Serializable {

    private Venta current;
    private DataModel items = null;
    @EJB
    private JP.VentaFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public VentaController() {
    }

    public Venta getSelected() {
        if (current == null) {
            current = new Venta();
            selectedItemIndex = -1;
        }
        return current;
    }

    private VentaFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List.xhtml?faces-redirect=true";
    }

    public String prepareView() {
        current = (Venta) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Venta();
        selectedItemIndex = -1;
       return "Create.xhtml?faces-redirect=true";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("VentaCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Venta) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("VentaUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Venta) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("VentaDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Venta getVenta(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Venta.class)
    public static class VentaControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            VentaController controller = (VentaController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "ventaController");
            return controller.getVenta(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Venta) {
                Venta o = (Venta) object;
                return getStringKey(o.getVentaID());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Venta.class.getName());
            }
        }

    }

}

web/venta/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
 <h:head>
        <title>INICIO</title>
        <link href="../resources/css/estilo_inicio.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body style="background-color:#FAFAFA">
     <img src="../resources/images/LOGO.png" width="400px" height="99"/><br/>
     <h:form><ul>
        <li><a href="../producto/Create.xhtml">REGISTRAR PRODUCTO</a></li>
        <li><a class="active" href="">REGISTRAR VENTA</a></li>
        <li><a href="../producto/List.xhtml">UNIDADES EN STOCK</a></li>
        <li style="float:right;"><a href=""  class="active">▼ OPCIONES</a>
        <ul>
          <li><a class="lis" href="">AGREGAR USUARIO</a></li>
          <li><a class="lis" href="">AGREGAR PROVEEDOR</a></li>
          <li><a class="lis" href="">AGREGAR CLIENTE</a></li>
          <li><a class="lis" href="">CERRAR SESION</a></li>
        </ul>
      </li>
         </ul>
     </h:form><br/>
            <h:form>
                  <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateVentaLabel_ventaID}" for="ventaID" />
                    <h:inputText id="ventaID" value="#{ventaController.selected.ventaID}" title="#{bundle.CreateVentaTitle_ventaID}" required="true" requiredMessage="#{bundle.CreateVentaRequiredMessage_ventaID}"/>
                    <h:outputLabel value="#{bundle.CreateVentaLabel_fechaVenta}" for="fechaVenta" />
                    <h:inputText id="fechaVenta" value="#{ventaController.selected.fechaVenta}" title="#{bundle.CreateVentaTitle_fechaVenta}" required="true" requiredMessage="#{bundle.CreateVentaRequiredMessage_fechaVenta}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateVentaLabel_clienteID}" for="clienteID" />
                    <h:selectOneMenu id="clienteID" value="#{ventaController.selected.clienteID}" title="#{bundle.CreateVentaTitle_clienteID}" required="true" requiredMessage="#{bundle.CreateVentaRequiredMessage_clienteID}">
                        <f:selectItems value="#{clienteController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateVentaLabel_productID}" for="productID" />
                    <h:selectOneMenu id="productID" value="#{ventaController.selected.productID}" title="#{bundle.CreateVentaTitle_productID}" required="true" requiredMessage="#{bundle.CreateVentaRequiredMessage_productID}">
                        <f:selectItems value="#{productoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <p:commandButton class="volver" action="#{ventaController.create}" value="#{bundle.CreateVentaSaveLink}" />
                <br />
                <br />
                <p:commandButton class="volver" action="#{ventaController.prepareList}" value="Ver todas las ventas" immediate="true"/>
            </h:form>
    </h:body>

</html>

web/venta/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditVentaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditVentaLabel_ventaID}" for="ventaID" />
                    <h:inputText id="ventaID" value="#{ventaController.selected.ventaID}" title="#{bundle.EditVentaTitle_ventaID}" required="true" requiredMessage="#{bundle.EditVentaRequiredMessage_ventaID}"/>
                    <h:outputLabel value="#{bundle.EditVentaLabel_fechaVenta}" for="fechaVenta" />
                    <h:inputText id="fechaVenta" value="#{ventaController.selected.fechaVenta}" title="#{bundle.EditVentaTitle_fechaVenta}" required="true" requiredMessage="#{bundle.EditVentaRequiredMessage_fechaVenta}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditVentaLabel_clienteID}" for="clienteID" />
                    <h:selectOneMenu id="clienteID" value="#{ventaController.selected.clienteID}" title="#{bundle.EditVentaTitle_clienteID}" required="true" requiredMessage="#{bundle.EditVentaRequiredMessage_clienteID}">
                        <f:selectItems value="#{clienteController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditVentaLabel_productID}" for="productID" />
                    <h:selectOneMenu id="productID" value="#{ventaController.selected.productID}" title="#{bundle.EditVentaTitle_productID}" required="true" requiredMessage="#{bundle.EditVentaRequiredMessage_productID}">
                        <f:selectItems value="#{productoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{ventaController.update}" value="#{bundle.EditVentaSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditVentaViewLink}"/>
                <br />
                <h:commandLink action="#{ventaController.prepareList}" value="#{bundle.EditVentaShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditVentaIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/venta/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListVentaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListVentaEmpty}" rendered="#{ventaController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{ventaController.items.rowCount > 0}">
                    <h:outputText value="#{ventaController.pagination.pageFirstItem + 1}..#{ventaController.pagination.pageLastItem + 1}/#{ventaController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{ventaController.previous}" value="#{bundle.Previous} #{ventaController.pagination.pageSize}" rendered="#{ventaController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{ventaController.next}" value="#{bundle.Next} #{ventaController.pagination.pageSize}" rendered="#{ventaController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{ventaController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVentaTitle_ventaID}"/>
                            </f:facet>
                            <h:outputText value="#{item.ventaID}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVentaTitle_fechaVenta}"/>
                            </f:facet>
                            <h:outputText value="#{item.fechaVenta}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVentaTitle_clienteID}"/>
                            </f:facet>
                            <h:outputText value="#{item.clienteID}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListVentaTitle_productID}"/>
                            </f:facet>
                            <h:outputText value="#{item.productID}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{ventaController.prepareView}" value="#{bundle.ListVentaViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{ventaController.prepareEdit}" value="#{bundle.ListVentaEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{ventaController.destroy}" value="#{bundle.ListVentaDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{ventaController.prepareCreate}" value="#{bundle.ListVentaCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListVentaIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/venta/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewVentaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewVentaLabel_ventaID}"/>
                    <h:outputText value="#{ventaController.selected.ventaID}" title="#{bundle.ViewVentaTitle_ventaID}"/>
                    <h:outputText value="#{bundle.ViewVentaLabel_fechaVenta}"/>
                    <h:outputText value="#{ventaController.selected.fechaVenta}" title="#{bundle.ViewVentaTitle_fechaVenta}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewVentaLabel_clienteID}"/>
                    <h:outputText value="#{ventaController.selected.clienteID}" title="#{bundle.ViewVentaTitle_clienteID}"/>
                    <h:outputText value="#{bundle.ViewVentaLabel_productID}"/>
                    <h:outputText value="#{ventaController.selected.productID}" title="#{bundle.ViewVentaTitle_productID}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{ventaController.destroyAndView}" value="#{bundle.ViewVentaDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewVentaEditLink}"/>
                <br />
                <h:commandLink action="#{ventaController.prepareCreate}" value="#{bundle.ViewVentaCreateLink}" />
                <br />
                <h:commandLink action="#{ventaController.prepareList}" value="#{bundle.ViewVentaShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewVentaIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>